project:
  type: website
  output-dir: docs
  
website:
  title: "ASPAS"
  site-url: https://webs.uvigo.es/asanchez
#  description: "Site da asignatura Experimentación en Química Industrial 1"
  navbar:
    search: true
    right:
      
      - icon: github
        href: https://github.com/anxosanchez
      - icon: twitter
        href: https://www.titter.con/anxosanchez
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - posts.qmd
  margin-header: subscribe.html

format:
  html:
    theme: 
      dark: darkly
      light: flatly
      
    css: styles.css
    toc: true

