project:
  type: website
  output-dir: public

website:
  title: "ASPAS"
  navbar:
    left:
      - text: "Inicio"
        file: index.qmd
      - about.qmd
      - blog.qmd   
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme: 
      dark: solar
      light: morph
      
    css: styles.css
    toc: true

