project:
  type: website
  output-dir: public

website:
  title: "ASPAS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd   
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme: 
      dark: solar
      light: morph
      
    css: styles.css
    toc: true

